[project]
name = "image-guesser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.13.0",
    "click==8.3.3",
    "colorama==0.4.6",
    "fastapi==0.136.1",
    "fastapi-cli==0.0.24",
    "fastapi-utils==0.8.0",
    "h11==0.16.0",
    "httptools==0.7.1",
    "idna==3.13",
    "markdown-it-py==4.0.0",
    "mdurl==0.1.2",
    "psutil==5.9.8",
    "pydantic==2.13.3",
    "pydantic-core==2.46.3",
    "pygments==2.20.0",
    "python-dotenv==1.2.2",
    "pyyaml==6.0.3",
    "rich==15.0.0",
    "rich-toolkit==0.19.7",
    "shellingham==1.5.4",
    "starlette==1.0.0",
    "typer==0.25.0",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "uvicorn==0.46.0",
    "watchfiles==1.1.1",
    "websockets==16.0",
]
